### ISSUE TITLE
Missing Files

### ISSUE THREAD

**Issue by zjedwin** [growiat/intro-data-capstone-biodiversity#1]
Hi there,

My name is Zamar and I work on the Codecademy Project Review team. I was attempting to review your project, but was not able to, because you’re missing your python files. I read your readme.txt but we cannot access your learning environment directly. 

In order to receive a review, please upload the missing file directly to your project repo using these instructions. 

Once you’ve completed your project and uploaded it to this repo, you will be able to receive a review. To do so, **please notify Customer Support by submitting a request via [this form](https://help.codecademy.com/hc/en-us/requests/new)**. 

Fill out the form using the following template:
```
*Subject*: Request for Project Review

*Description*:

I am submitting a project for review as there was an error with my previous submission. 

Please see information below:

Intensive Name:
Cohort Start Date:
 Project Title:
Git Repo Link:
```

Thanks,
Zamar & the Codecademy Team

**Comment by growiat** [comment]
Hi Zamar,
I don't see any instructions here, and I have tried looking elsewhere to no avail. 
Thanks Grace
